"""Smoke-training loop for the fixed dense baseline (Phase A Task 003).

`run_smoke_training` trains `DecoderOnlyTransformer` on a tiny deterministic
dataset generated by `apc.environments`, writes the run artifact layout
described in `README.md` (`config.yaml`, `metrics.jsonl`, `summary.json`,
`system.json`, `checkpoint/`), and then reloads the saved checkpoint into a
fresh model to verify it reproduces the trained model's greedy outputs
exactly. `scripts/smoke_train.py` is a thin CLI wrapper around this function.
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import torch
import torch.nn.functional as F
from torch import nn

from apc.core.checkpoint import load_checkpoint, save_checkpoint
from apc.core.data import IGNORE_INDEX, collate_batch
from apc.core.generation import evaluate_exact_match
from apc.core.model import DecoderOnlyTransformer, TransformerConfig
from apc.core.tokens import build_special_tokens
from apc.environments.generator import TaskGenerator
from apc.environments.vocab import DEFAULT_VOCAB_SIZE
from apc.utils.config import save_config
from apc.utils.seed import set_seed
from apc.utils.system_info import get_system_info


@dataclass(frozen=True)
class DataConfig:
    vocab_size: int = DEFAULT_VOCAB_SIZE
    sequence_length_range: tuple[int, int] = (6, 10)
    max_depth: int = 2
    novel_composition_fraction: float = 0.3
    num_examples: int = 16


@dataclass(frozen=True)
class OptimConfig:
    steps: int = 300
    lr: float = 3e-4
    weight_decay: float = 0.01
    grad_clip: float = 1.0
    log_every: int = 20
    device: str = "auto"
    amp: bool = False


@dataclass(frozen=True)
class SmokeTrainConfig:
    run_name: str
    seed: int
    output_dir: str
    data: DataConfig
    model: dict[str, Any]
    optim: OptimConfig


def smoke_config_from_dict(raw: dict[str, Any]) -> SmokeTrainConfig:
    """Parse a `configs/phase_a_smoke.yaml`-shaped dict into `SmokeTrainConfig`.

    `model` is kept as a plain dict (rather than a dataclass) because it is
    passed straight through to `TransformerConfig`, which already validates
    and defaults its own fields; `vocab_size` is filled in later once the
    environment vocabulary (and its special tokens) is known.
    """
    data_raw = raw.get("data", {})
    optim_raw = raw.get("optim", {})
    return SmokeTrainConfig(
        run_name=raw.get("run_name", "phase_a_smoke"),
        seed=raw.get("seed", 0),
        output_dir=raw.get("output_dir", "runs"),
        data=DataConfig(
            vocab_size=data_raw.get("vocab_size", DEFAULT_VOCAB_SIZE),
            sequence_length_range=tuple(data_raw.get("sequence_length_range", (6, 10))),
            max_depth=data_raw.get("max_depth", 2),
            novel_composition_fraction=data_raw.get("novel_composition_fraction", 0.3),
            num_examples=data_raw.get("num_examples", 16),
        ),
        model=dict(raw.get("model", {})),
        optim=OptimConfig(
            steps=optim_raw.get("steps", 300),
            lr=optim_raw.get("lr", 3e-4),
            weight_decay=optim_raw.get("weight_decay", 0.01),
            grad_clip=optim_raw.get("grad_clip", 1.0),
            log_every=optim_raw.get("log_every", 20),
            device=optim_raw.get("device", "auto"),
            amp=optim_raw.get("amp", False),
        ),
    )


def resolve_device(name: str) -> torch.device:
    if name == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(name)


def _resolved_config_dict(
    config: SmokeTrainConfig, model_config: TransformerConfig
) -> dict[str, Any]:
    """A fully-resolved (defaults applied) config dict, safe to dump as YAML."""
    raw = {
        "run_name": config.run_name,
        "seed": config.seed,
        "output_dir": config.output_dir,
        "data": asdict(config.data),
        "model": asdict(model_config),
        "optim": asdict(config.optim),
    }
    # Round-trip through JSON to turn tuples into lists (yaml.safe_dump has
    # no default representer for tuples).
    return json.loads(json.dumps(raw))


def run_smoke_training(config: SmokeTrainConfig, run_dir: str | Path) -> dict[str, Any]:
    """Train, checkpoint, and reload-verify the baseline; returns the summary dict
    also written to `run_dir/summary.json`."""
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)

    set_seed(config.seed)
    device = resolve_device(config.optim.device)

    specials = build_special_tokens(config.data.vocab_size)
    generator = TaskGenerator(
        seed=config.seed,
        vocab_size=config.data.vocab_size,
        sequence_length_range=config.data.sequence_length_range,
        max_depth=config.data.max_depth,
        novel_composition_fraction=config.data.novel_composition_fraction,
    )
    examples = generator.generate(config.data.num_examples, split="train")
    batch = collate_batch(examples, specials, device=device)

    model_config = TransformerConfig(vocab_size=specials.model_vocab_size, **config.model)
    model = DecoderOnlyTransformer(model_config).to(device)
    optimizer = torch.optim.AdamW(
        model.parameters(), lr=config.optim.lr, weight_decay=config.optim.weight_decay
    )
    use_amp = config.optim.amp and device.type == "cuda"

    metrics_path = run_dir / "metrics.jsonl"
    start_time = time.perf_counter()
    final_loss = float("nan")
    with metrics_path.open("w", encoding="utf-8") as metrics_file:
        for step in range(1, config.optim.steps + 1):
            model.train()
            optimizer.zero_grad(set_to_none=True)
            with torch.autocast(device_type="cuda", dtype=torch.bfloat16, enabled=use_amp):
                logits = model(batch.input_ids)
                loss = F.cross_entropy(
                    logits.reshape(-1, logits.size(-1)),
                    batch.labels.reshape(-1),
                    ignore_index=IGNORE_INDEX,
                )
            loss.backward()
            if config.optim.grad_clip > 0:
                nn.utils.clip_grad_norm_(model.parameters(), config.optim.grad_clip)
            optimizer.step()
            final_loss = float(loss.item())

            if step % config.optim.log_every == 0 or step == config.optim.steps:
                metrics_file.write(json.dumps({"step": step, "loss": final_loss}) + "\n")
                metrics_file.flush()

    wall_clock_seconds = time.perf_counter() - start_time
    train_exact_match, predictions = evaluate_exact_match(model, examples, specials, device)

    checkpoint_path = run_dir / "checkpoint" / "model.pt"
    resolved_config = _resolved_config_dict(config, model_config)
    save_checkpoint(checkpoint_path, model, optimizer, config.optim.steps, resolved_config)
    save_config(resolved_config, run_dir / "config.yaml")
    system_info = get_system_info(seed=config.seed)
    (run_dir / "system.json").write_text(json.dumps(system_info, indent=2), encoding="utf-8")

    # Reload check: a fresh model/optimizer loaded from disk must reproduce
    # the trained model's greedy outputs exactly (Task 003 acceptance).
    reload_model = DecoderOnlyTransformer(model_config).to(device)
    reload_optimizer = torch.optim.AdamW(
        reload_model.parameters(), lr=config.optim.lr, weight_decay=config.optim.weight_decay
    )
    load_checkpoint(checkpoint_path, reload_model, reload_optimizer, map_location=str(device))
    reload_exact_match, reload_predictions = evaluate_exact_match(
        reload_model, examples, specials, device
    )

    summary = {
        "run_name": config.run_name,
        "seed": config.seed,
        "steps": config.optim.steps,
        "final_loss": final_loss,
        "train_exact_match": train_exact_match,
        "reload_exact_match": reload_exact_match,
        "reload_matches_outputs": reload_predictions == predictions,
        "param_count": model.num_parameters(),
        "trainable_param_count": model.num_parameters(trainable_only=True),
        "wall_clock_seconds": wall_clock_seconds,
        "peak_vram_bytes": system_info["peak_vram_bytes"],
        "num_examples": len(examples),
    }
    (run_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary
